server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    loadbalancer:
      ribbon:
#        Not needed since we excluded the dependency but
#        Still good to add it here for better readability
        enabled: false
    consul:
      enabled: true
      discovery:
#        Get only services that are passing the health check
        query-passing: true
#      bootstrap properties
#      config:
##        enabled: false
#        data-key: application.yml
#        prefix: config
#        format: yaml
#        default-context: defaults
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication/
          predicates:
            - Path=/challenges/**, /attempts, /attempts/**, /users/**
        - id: gamification
          uri: lb://gamification/
          predicates:
            - Path=/leaders
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"

#      default-filters:
#        - name: Retry
#          args:
#            retries: 3
#            methods: GET, POST

# Comes with centralised log back
logging:
  level:
    org.springframework.amqp.rabbit.connection.CachingConnectionFactory: WARN

#logging:
#  level:
#    org.springframework.cloud.gateway.handler.predicate: trace




